# Generated by Django 4.0.4 on 2023-06-10 01:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image_file', models.ImageField(upload_to='images/')),
                ('date_created', models.DateTimeField(default=datetime.date(2023, 6, 9))),
            ],
        ),
    ]
