# Generated by Django 4.0.4 on 2023-06-11 07:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0003_publicacion_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='date_created',
            field=models.DateTimeField(default=datetime.date(2023, 6, 11)),
        ),
    ]
