# Generated by Django 4.0.4 on 2023-06-13 02:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0004_alter_publicacion_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='date_created',
            field=models.DateTimeField(default=datetime.date(2023, 6, 12)),
        ),
    ]
